version: "3"

services:
  ###> doctrine/doctrine-bundle ###
  database:
    container_name: sortileges-db
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-sortileges}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
      POSTGRES_USER: ${POSTGRES_USER:-root}
    healthcheck:
      test: pg_isready
    ports:
      - "5432:5432"
      # volumes:
      #   - db-data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
  ###< doctrine/doctrine-bundle ###

  test-database:
    container_name: sortileges-test-db
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_TEST_DB:-sortileges-test}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_TEST_PASSWORD:-root}
      POSTGRES_USER: ${POSTGRES_TEST_USER:-root}
    healthcheck:
      test: pg_isready
    ports:
      - "5433:5432"

volumes:
  ###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
